In [12]:
import numpy as np
ranvec = np.random.randint(1, 21, size=15)
array1 = ranvec.reshape(3, 5)
print("Array Shape:", array1.shape)
print("Array before modification:\n", array1)
for i in range(array1.shape[0]):
    max = array1[i].argmax()
    array1[i, max] = 0

print("Modified Array:\n",array1)

Array Shape: (3, 5)
Array before modification:
 [[10 16 15 20 20]
 [19  1  9 10 15]
 [ 3 14 16  7 13]]
Modified Array:
 [[10 16 15  0 20]
 [ 0  1  9 10 15]
 [ 3 14  0  7 13]]


In [3]:
array1 = np.random.randint(1, 10, size=(4, 3), dtype=np.int32)
print("Shape of the array:", array1.shape)
print("Type of the array:", type(array1))
print("Data type of the array:", array1.dtype)

Shape of the array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array: int32


In [4]:
A = np.array([[3, -2], [1, 0]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [2. 1.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [7]:
array = np.array([[0, 1, 2], [3, 4, 5]])
sum = np.trace(array)
print("Sum of diagonal elements:", sum)

Sum of diagonal elements: 4


In [6]:
original_array = np.array([[1, 2], [3, 4], [5, 6]])
reshaped_array = original_array.reshape(2, 3)

print("Reshaped Array (2x3):\n", reshaped_array)

Reshaped Array (2x3):
 [[1 2 3]
 [4 5 6]]
